"""
report.py - Report generation (Task 5).

Interface:
    generate(domain, results, fmt="json") -> filepath string
"""

# def generate(domain, results, fmt="json"):
#     # TODO: Task 5 teammate implements this
#     return ""
"""
report.py - Report generation (Task 5).

Interface:
    generate(domain, results, fmt="json") -> filepath string

Supports three output formats:
    - "json": raw structured dump of all module results.
    - "txt":  plain-text summary, easy to read in a terminal or paste
              into a ticket.
    - "html": a styled, shareable HTML report (uses jinja2 if available,
              otherwise falls back to a simple manual template so the
              module still works without the dependency installed).
"""

import json
import logging
import os
from datetime import datetime

try:
    from jinja2 import Template
    HAS_JINJA2 = True
except ImportError:
    HAS_JINJA2 = False

logger = logging.getLogger(__name__)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORTS_DIR = os.path.join(BASE_DIR, "reports")

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Recon Report - {{ domain }}</title>
<style>
  body { font-family: -apple-system, Segoe UI, Arial, sans-serif; margin: 0; padding: 2rem;
         background: #0f1115; color: #e6e6e6; }
  h1 { color: #7dd3fc; margin-bottom: 0; }
  .subtitle { color: #9ca3af; margin-top: 0.25rem; }
  .module { background: #1a1d24; border: 1px solid #2a2e37; border-radius: 8px;
            padding: 1.25rem 1.5rem; margin: 1.25rem 0; }
  .module h2 { margin-top: 0; color: #f0abfc; font-size: 1.1rem; text-transform: uppercase;
               letter-spacing: 0.05em; }
  .status-ok { color: #4ade80; }
  .status-error { color: #f87171; }
  .status-other { color: #facc15; }
  pre { background: #0b0d11; padding: 1rem; border-radius: 6px; overflow-x: auto;
        white-space: pre-wrap; word-break: break-word; }
  table { border-collapse: collapse; width: 100%; margin-top: 0.5rem; }
  th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #2a2e37; }
  th { color: #9ca3af; font-weight: 600; }
  footer { margin-top: 2rem; color: #6b7280; font-size: 0.85rem; }
</style>
</head>
<body>
  <h1>Recon Report</h1>
  <p class="subtitle">Target: <strong>{{ domain }}</strong> &middot; Generated {{ generated_at }}</p>

  {% for name, data in results.items() %}
  <div class="module">
    <h2>{{ name }}</h2>
    {% set status = data.get("status", "error" if "error" in data else "ok") %}
    <p>
      Status:
      <span class="{{ 'status-error' if 'error' in data else ('status-ok' if status == 'ok' else 'status-other') }}">
        {{ "error" if "error" in data else status }}
      </span>
    </p>
    <pre>{{ data | tojson(indent=2) }}</pre>
  </div>
  {% endfor %}

  <footer>Generated by Offensive Recon Tool</footer>
</body>
</html>
"""


def _ensure_reports_dir():
    os.makedirs(REPORTS_DIR, exist_ok=True)


def _timestamped_path(domain, ext):
    safe_domain = domain.replace("/", "_").replace(":", "_")
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"recon_{safe_domain}_{ts}.{ext}"
    return os.path.join(REPORTS_DIR, filename)


def _generate_json(domain, results, generated_at):
    path = _timestamped_path(domain, "json")
    payload = {
        "domain": domain,
        "generated_at": generated_at,
        "results": results,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, default=str)
    return path


def _generate_txt(domain, results, generated_at):
    path = _timestamped_path(domain, "txt")
    lines = []
    lines.append("=" * 60)
    lines.append("OFFENSIVE RECON TOOL - REPORT")
    lines.append("=" * 60)
    lines.append(f"Target:       {domain}")
    lines.append(f"Generated at: {generated_at}")
    lines.append("")

    for name, data in results.items():
        lines.append("-" * 60)
        lines.append(f"MODULE: {name}")
        lines.append("-" * 60)
        if isinstance(data, dict) and "error" in data:
            lines.append(f"  [ERROR] {data['error']}")
        elif isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, (list, tuple)):
                    lines.append(f"  {key}:")
                    if value:
                        for item in value:
                            lines.append(f"    - {item}")
                    else:
                        lines.append("    (none)")
                elif isinstance(value, dict):
                    lines.append(f"  {key}:")
                    if value:
                        for k, v in value.items():
                            lines.append(f"    {k}: {v}")
                    else:
                        lines.append("    (none)")
                else:
                    lines.append(f"  {key}: {value}")
        else:
            lines.append(f"  {data}")
        lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def _generate_html(domain, results, generated_at):
    path = _timestamped_path(domain, "html")

    if HAS_JINJA2:
        template = Template(HTML_TEMPLATE)
        html = template.render(domain=domain, results=results, generated_at=generated_at)
    else:
        # Manual fallback so the module still works without jinja2 installed.
        logger.warning("jinja2 not installed; falling back to basic HTML template.")
        sections = []
        for name, data in results.items():
            sections.append(
                f"<div class='module'><h2>{name}</h2>"
                f"<pre>{json.dumps(data, indent=2, default=str)}</pre></div>"
            )
        html = (
            "<!DOCTYPE html><html><head><meta charset='utf-8'>"
            f"<title>Recon Report - {domain}</title></head><body>"
            f"<h1>Recon Report</h1><p>Target: {domain} &middot; Generated {generated_at}</p>"
            + "".join(sections)
            + "</body></html>"
        )

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    return path


def generate(domain, results, fmt="json"):
    _ensure_reports_dir()
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    generators = {
        "json": _generate_json,
        "txt": _generate_txt,
        "html": _generate_html,
    }

    generator = generators.get(fmt)
    if generator is None:
        logger.error("Unknown report format '%s', defaulting to json.", fmt)
        generator = _generate_json

    try:
        path = generator(domain, results, generated_at)
        logger.info("Report written to %s", path)
        return path
    except Exception as e:
        logger.error("Failed to generate %s report: %s", fmt, e)
        return ""